package studio.obsifox.launcher.desktop

object StringTables {
    val en: Map<String, String> = mapOf(
        // navigation
        "nav_home" to "Home", "nav_instances" to "Profiles", "nav_browse" to "Modrinth", "nav_accounts" to "Accounts",
        "nav_settings" to "Settings", "nav_console" to "Console",
        // common
        "ok" to "OK", "cancel" to "Cancel", "close" to "Close", "save" to "Save", "delete" to "Delete", "create" to "Create",
        "install" to "Install", "installed" to "Installed", "update" to "Update", "remove" to "Remove", "search" to "Search",
        "loading" to "Loading…", "retry" to "Retry", "back" to "Back", "copy" to "Copy", "copied" to "Copied",
        "open_folder" to "Open folder", "open_in_browser" to "Open in browser", "none" to "None", "auto" to "Automatic",
        "error" to "Something went wrong", "details" to "Details", "select" to "Select", "active" to "Active",
        // home
        "home_title" to "Ready to play?", "home_sub" to "Pick a profile and an account, then jump in.",
        "play" to "Play", "playing" to "Running", "stop" to "Stop", "running" to "Running",
        "last_played" to "Last played: %s", "never_played" to "Never played", "play_time" to "Play time: %s",
        "no_instance_title" to "No profiles yet", "no_instance_text" to "Create a profile to install a Minecraft version and a mod loader.",
        "create_instance" to "Create profile", "recent" to "Your profiles", "playing_as" to "Playing as",
        "no_account" to "Add an account first", "dur_hm" to "%dh %dm", "dur_m" to "%d min",
        // instances
        "instances_title" to "Profiles", "new_instance" to "New profile", "import_mrpack" to "Import .mrpack",
        "instance_name" to "Profile name", "mc_version" to "Minecraft version", "loader" to "Mod loader", "loader_version" to "Loader version",
        "show_snapshots" to "Show snapshots", "version_filter" to "Filter versions", "latest" to "latest", "recommended" to "recommended",
        "empty_instances" to "Nothing here yet. Create your first profile!", "duplicate" to "Duplicate", "copy_suffix" to "%s (copy)",
        "delete_title" to "Delete profile?", "delete_text" to "\"%s\" and all of its worlds, mods and settings will be permanently deleted.",
        "profile_settings" to "Settings", "launch_failed" to "Could not start the game",
        // instance detail
        "tab_mods" to "Mods", "tab_resourcepacks" to "Resource packs", "tab_shaders" to "Shaders", "tab_settings" to "Settings",
        "java_path" to "Java executable", "java_auto" to "Automatic (recommended)", "memory_max" to "Maximum memory", "memory_min" to "Initial memory",
        "jvm_args" to "JVM arguments", "game_args" to "Game arguments", "resolution" to "Window size", "width" to "Width", "height" to "Height",
        "fullscreen" to "Fullscreen", "auto_join" to "Join server on launch", "auto_join_hint" to "host or host:port, optional", "notes" to "Notes",
        "check_updates" to "Check for updates", "updates_found" to "%d update(s) available", "no_updates" to "Everything is up to date",
        "update_all" to "Update all", "add_from_modrinth" to "Add from Modrinth", "no_content" to "Nothing installed here yet.",
        "identify" to "Recognise files", "identified" to "%d file(s) recognised", "unknown_source" to "Unknown source",
        "loader_none_hint" to "This is a vanilla profile: mods need Fabric, Quilt, Forge or NeoForge.", "saved" to "Saved",
        // browse
        "browse_title" to "Modrinth", "search_hint" to "Search mods, modpacks, packs and shaders…",
        "type_mod" to "Mods", "type_modpack" to "Modpacks", "type_resourcepack" to "Resource packs", "type_shader" to "Shaders",
        "sort_by" to "Sort by", "sort_relevance" to "Relevance", "sort_downloads" to "Downloads", "sort_follows" to "Follows", "sort_newest" to "Newest", "sort_updated" to "Updated",
        "target_profile" to "Install into", "load_more" to "Load more", "downloads_count" to "%s downloads", "by_author" to "by %s",
        "choose_version" to "Choose version", "no_results" to "No results", "no_compatible" to "No compatible version for %s",
        "installed_ok" to "Installed %s", "installed_with_deps" to "Installed %s (+%d dependencies)", "view_on_modrinth" to "View on Modrinth",
        "need_profile" to "Create a profile first", "modpack_installed" to "Modpack \"%s\" is ready", "any_game_version" to "All versions",
        "pick_version_title" to "Pick a version of %s", "version_meta" to "%s · %s", "filter_compatible" to "Only compatible with this profile",
        // accounts
        "accounts_title" to "Accounts", "add_offline" to "Add offline account",
        "offline_name" to "Player name", "offline_hint" to "1–16 letters, digits or underscore", "account_offline" to "Offline", "remove_account" to "Remove account", "offline_note" to "Offline accounts cannot join online-mode servers.",
        "no_accounts" to "No accounts yet.",
        // settings
        "settings_title" to "Settings", "language" to "Language", "lang_auto" to "System default", "memory_default" to "Default maximum memory",
        "jvm_default" to "Default JVM arguments", "java_override" to "Use this Java for every profile", "threads" to "Parallel downloads",
        "mirror" to "Download source", "mirror_official" to "Official servers", "mirror_bmcl" to "BMCLAPI mirror (for regions where Mojang is slow)",
        "proxy" to "HTTP proxy", "proxy_host" to "Host", "proxy_port" to "Port", "hide_launcher" to "Minimise the launcher while the game runs",
        "open_console" to "Open the console when the game starts", "data_dir" to "Data folder", "about" to "About", "version" to "Version",
        "about_text" to "ObsiLauncher is an unofficial launcher. Minecraft is a trademark of Mojang AB / Microsoft; this project is not affiliated with them.",
        "apply" to "Apply", "memory_auto" to "Auto", "restart_hint" to "Language changes apply instantly.",
        // tasks & stages
        "launching" to "Launching %s", "creating" to "Creating %s", "installing" to "Installing %s", "stage_resolving" to "Preparing…",
        "stage_libraries" to "Downloading libraries", "stage_assets" to "Downloading game assets", "stage_java" to "Preparing Java",
        "stage_loader" to "Downloading loader installer", "stage_modpack" to "Downloading modpack", "stage_modpack_files" to "Downloading modpack files",
        "stage_download" to "Downloading %s", "task_failed" to "Failed", "task_done" to "Done", "task_cancel" to "Cancel",
        // console / crash
        "console_title" to "Console", "console_empty" to "No game is running. Start a profile to see its output here.", "kill" to "Kill",
        "crash_title" to "The game stopped unexpectedly", "crash_text" to "\"%s\" exited with code %d. The last lines of its output:", "view_log" to "Open full log",
        "copy_log" to "Copy log", "game_exited" to "The game exited", "console_running" to "Running · PID %d",
        // gate
        "gate_brand" to "ObsiLauncher", "gate_checking" to "Checking launcher update", "gate_checking_sub" to "Contacting the update channel",
        "gate_verifying" to "Verifying your setup", "gate_verifying_sub" to "Looking at the data folder",
        "gate_ready" to "You're up to date", "gate_ready_sub" to "Everything is ready. Have fun!",
        "gate_available" to "A newer build is available", "gate_available_sub" to "Version %s — you can keep playing with this build.",
        "gate_offline" to "Offline — skipping the check", "gate_offline_sub" to "No connection. Your profiles and worlds still work.",
        "gate_failed" to "Update check failed", "gate_continue" to "Continue", "gate_continue_offline" to "Continue offline",
        "gate_recheck" to "Recheck", "gate_open_page" to "Open release page",
        "gate_footer" to "An unofficial Minecraft launcher by ObsiFox Studio",
        "gate_footer_offline" to "Offline copy — update check and online art skipped",
        // living theme
        "stat_install" to "Install", "stat_playtime" to "Play time", "stat_last" to "Last played",
        "ready_status" to "READY", "offline_status" to "OFFLINE", "art_loading" to "Downloading official artwork…", "fs_toggle" to "Fullscreen",
        "theme_vanilla" to "Vanilla", "theme_vanilla_desc" to "Warm dark surfaces with the classic orange accent",
        "theme_white" to "Daylight", "theme_white_desc" to "A light, calm surface for bright rooms",
        "theme_black" to "Midnight", "theme_black_desc" to "Near-black, for dark rooms",
        "appearance" to "Appearance", "appearance_hint" to "Theme, launcher art and how they blend together.",
        "bg_version" to "Match the profile", "bg_version_desc" to "Official wallpaper of the selected Minecraft version",
        "bg_latest" to "Always newest", "bg_latest_desc" to "Latest official wallpaper on every screen",
        "bg_custom" to "My own image", "bg_custom_desc" to "Pick a PNG or JPG from your disk",
        "bg_pick" to "Choose a wallpaper image",
        "bg_version_old" to "Profiles older than 1.12.2 use the classic PC wallpaper bundle.",
        "adapt_colors" to "Adapt colours to the art", "adapt_colors_desc" to "The launcher picks its accent from the wallpaper's palette.",
        "video_note" to "Animated/video wallpapers arrive in a later update.",
        // first-run wizard
        "continue" to "Continue", "wiz_first" to "FIRST RUN", "wiz_steps" to "SETUP",
        "wiz_step_theme" to "Theme", "wiz_step_bg" to "Launcher art", "wiz_step_acc" to "Local account",
        "wiz_hint" to "You can change all of this later in Settings.",
        "wiz_kicker" to "Welcome to ObsiLauncher", "wiz_t1" to "Pick a look", "wiz_d1" to "The surface theme of the launcher.",
        "wiz_t2" to "What should the background show?", "wiz_d2" to "Official Minecraft wallpapers, matched to your profiles.",
        "wiz_t3" to "Add a local account", "wiz_d3" to "Offline accounts only — stored on this device.",
        "wiz_step_of" to "Step %d of 3", "wiz_finish" to "Finish", "account_empty" to "No local accounts yet.",
        "local_only_note" to "Accounts are stored on this device only; no Microsoft sign-in, no remote servers.",
    )

    val fa: Map<String, String> = mapOf(
        // navigation
        "nav_home" to "خانه", "nav_instances" to "پروفایل‌ها", "nav_browse" to "مودرینث", "nav_accounts" to "حساب‌ها",
        "nav_settings" to "تنظیمات", "nav_console" to "کنسول",
        // common
        "ok" to "باشه", "cancel" to "انصراف", "close" to "بستن", "save" to "ذخیره", "delete" to "حذف", "create" to "ساخت",
        "install" to "نصب", "installed" to "نصب شده", "update" to "به‌روزرسانی", "remove" to "حذف", "search" to "جستجو",
        "loading" to "در حال بارگذاری…", "retry" to "تلاش دوباره", "back" to "بازگشت", "copy" to "کپی", "copied" to "کپی شد",
        "open_folder" to "باز کردن پوشه", "open_in_browser" to "باز کردن در مرورگر", "none" to "هیچ", "auto" to "خودکار",
        "error" to "مشکلی پیش آمد", "details" to "جزئیات", "select" to "انتخاب", "active" to "فعال",
        // home
        "home_title" to "آماده‌ی بازی هستی؟", "home_sub" to "یک پروفایل و یک حساب انتخاب کن و وارد دنیا شو.",
        "play" to "شروع بازی", "playing" to "در حال اجرا", "stop" to "توقف", "running" to "در حال اجرا",
        "last_played" to "آخرین بازی: %s", "never_played" to "هنوز بازی نشده", "play_time" to "زمان بازی: %s",
        "no_instance_title" to "هنوز پروفایلی نداری", "no_instance_text" to "یک پروفایل بساز تا نسخه‌ی ماینکرافت و لودر دلخواهت نصب شود.",
        "create_instance" to "ساخت پروفایل", "recent" to "پروفایل‌های تو", "playing_as" to "بازی با نام",
        "no_account" to "اول یک حساب اضافه کن", "dur_hm" to "%d ساعت و %d دقیقه", "dur_m" to "%d دقیقه",
        // instances
        "instances_title" to "پروفایل‌ها", "new_instance" to "پروفایل جدید", "import_mrpack" to "وارد کردن فایل mrpack.",
        "instance_name" to "نام پروفایل", "mc_version" to "نسخه‌ی ماینکرافت", "loader" to "لودر مود", "loader_version" to "نسخه‌ی لودر",
        "show_snapshots" to "نمایش اسنپ‌شات‌ها", "version_filter" to "فیلتر نسخه‌ها", "latest" to "جدیدترین", "recommended" to "پیشنهادی",
        "empty_instances" to "اینجا هنوز چیزی نیست. اولین پروفایلت را بساز!", "duplicate" to "کپی‌برداری", "copy_suffix" to "%s (کپی)",
        "delete_title" to "پروفایل حذف شود؟", "delete_text" to "«%s» با همه‌ی دنیاها، مودها و تنظیماتش برای همیشه حذف می‌شود.",
        "profile_settings" to "تنظیمات", "launch_failed" to "اجرای بازی ممکن نشد",
        // instance detail
        "tab_mods" to "مودها", "tab_resourcepacks" to "ریسورس‌پک‌ها", "tab_shaders" to "شیدرها", "tab_settings" to "تنظیمات",
        "java_path" to "مسیر جاوا", "java_auto" to "خودکار (پیشنهادی)", "memory_max" to "حداکثر حافظه", "memory_min" to "حافظه‌ی اولیه",
        "jvm_args" to "آرگومان‌های JVM", "game_args" to "آرگومان‌های بازی", "resolution" to "اندازه‌ی پنجره", "width" to "عرض", "height" to "ارتفاع",
        "fullscreen" to "تمام‌صفحه", "auto_join" to "ورود خودکار به سرور", "auto_join_hint" to "host یا host:port ـ اختیاری", "notes" to "یادداشت",
        "check_updates" to "بررسی به‌روزرسانی", "updates_found" to "%d به‌روزرسانی موجود است", "no_updates" to "همه‌چیز به‌روز است",
        "update_all" to "به‌روزرسانی همه", "add_from_modrinth" to "افزودن از مودرینث", "no_content" to "اینجا هنوز چیزی نصب نشده.",
        "identify" to "شناسایی فایل‌ها", "identified" to "%d فایل شناسایی شد", "unknown_source" to "منبع نامشخص",
        "loader_none_hint" to "این پروفایل وانیلاست؛ برای مود باید Fabric، Quilt، Forge یا NeoForge داشته باشی.", "saved" to "ذخیره شد",
        // browse
        "browse_title" to "مودرینث", "search_hint" to "جستجوی مود، مادپک، ریسورس‌پک و شیدر…",
        "type_mod" to "مودها", "type_modpack" to "مادپک‌ها", "type_resourcepack" to "ریسورس‌پک‌ها", "type_shader" to "شیدرها",
        "sort_by" to "مرتب‌سازی", "sort_relevance" to "مرتبط‌ترین", "sort_downloads" to "بیشترین دانلود", "sort_follows" to "بیشترین دنبال‌کننده", "sort_newest" to "جدیدترین", "sort_updated" to "تازه به‌روز شده",
        "target_profile" to "نصب در", "load_more" to "نمایش بیشتر", "downloads_count" to "%s دانلود", "by_author" to "از %s",
        "choose_version" to "انتخاب نسخه", "no_results" to "نتیجه‌ای پیدا نشد", "no_compatible" to "نسخه‌ی سازگار برای %s پیدا نشد",
        "installed_ok" to "«%s» نصب شد", "installed_with_deps" to "«%s» نصب شد (+%d وابستگی)", "view_on_modrinth" to "مشاهده در مودرینث",
        "need_profile" to "اول یک پروفایل بساز", "modpack_installed" to "مادپک «%s» آماده است", "any_game_version" to "همه‌ی نسخه‌ها",
        "pick_version_title" to "انتخاب نسخه‌ی %s", "version_meta" to "%s · %s", "filter_compatible" to "فقط سازگار با این پروفایل",
        // accounts
        "accounts_title" to "حساب‌ها", "add_offline" to "افزودن حساب آفلاین",
        "offline_name" to "نام بازیکن", "offline_hint" to "۱ تا ۱۶ حرف انگلیسی، عدد یا زیرخط", "account_offline" to "آفلاین", "remove_account" to "حذف حساب", "offline_note" to "حساب آفلاین نمی‌تواند وارد سرورهای آنلاین‌مود شود.",
        "no_accounts" to "هنوز حسابی اضافه نشده.",
        // settings
        "settings_title" to "تنظیمات", "language" to "زبان", "lang_auto" to "پیش‌فرض سیستم", "memory_default" to "حداکثر حافظه‌ی پیش‌فرض",
        "jvm_default" to "آرگومان‌های JVM پیش‌فرض", "java_override" to "استفاده از این جاوا برای همه‌ی پروفایل‌ها", "threads" to "دانلود هم‌زمان",
        "mirror" to "منبع دانلود", "mirror_official" to "سرورهای رسمی", "mirror_bmcl" to "آینه‌ی BMCLAPI (برای مناطقی که Mojang کند است)",
        "proxy" to "پروکسی HTTP", "proxy_host" to "میزبان", "proxy_port" to "پورت", "hide_launcher" to "کوچک کردن لانچر هنگام اجرای بازی",
        "open_console" to "باز کردن کنسول هنگام شروع بازی", "data_dir" to "پوشه‌ی داده‌ها", "about" to "درباره", "version" to "نسخه",
        "about_text" to "ObsiLauncher یک لانچر غیررسمی است. Minecraft نشان تجاری Mojang AB / Microsoft است و این پروژه هیچ وابستگی‌ای به آن‌ها ندارد.",
        "apply" to "اعمال", "memory_auto" to "خودکار", "restart_hint" to "تغییر زبان بلافاصله اعمال می‌شود.",
        // tasks & stages
        "launching" to "در حال اجرای %s", "creating" to "در حال ساخت %s", "installing" to "در حال نصب %s", "stage_resolving" to "در حال آماده‌سازی…",
        "stage_libraries" to "دانلود کتابخانه‌ها", "stage_assets" to "دانلود فایل‌های بازی", "stage_java" to "آماده‌سازی جاوا",
        "stage_loader" to "دانلود نصب‌کننده‌ی لودر", "stage_modpack" to "دانلود مادپک", "stage_modpack_files" to "دانلود فایل‌های مادپک",
        "stage_download" to "دانلود %s", "task_failed" to "ناموفق", "task_done" to "انجام شد", "task_cancel" to "لغو",
        // console / crash
        "console_title" to "کنسول", "console_empty" to "بازی‌ای در حال اجرا نیست. یک پروفایل را اجرا کن تا خروجی‌اش اینجا نمایش داده شود.", "kill" to "بستن اجباری",
        "crash_title" to "بازی ناگهان متوقف شد", "crash_text" to "«%s» با کد %d بسته شد. آخرین خطوط خروجی:", "view_log" to "باز کردن لاگ کامل",
        "copy_log" to "کپی لاگ", "game_exited" to "بازی بسته شد", "console_running" to "در حال اجرا · PID %d",
        // gate
        "gate_brand" to "ObsiLauncher", "gate_checking" to "بررسی به‌روزرسانی لانچر", "gate_checking_sub" to "اتصال به کانال به‌روزرسانی",
        "gate_verifying" to "بررسی نصب فعلی", "gate_verifying_sub" to "نگاه به پوشه‌ی داده‌ها",
        "gate_ready" to "لانچر به‌روز است", "gate_ready_sub" to "همه‌چیز آماده است. خوش بگذره!",
        "gate_available" to "نسخه‌ی جدیدتری موجود است", "gate_available_sub" to "نسخه‌ی %s — با همین نسخه هم می‌توانی ادامه بدهی.",
        "gate_offline" to "آفلاین — رد شدن از بررسی", "gate_offline_sub" to "اتصالی نیست؛ پروفایل‌ها و دنیاهایت سر جایشانند.",
        "gate_failed" to "بررسی به‌روزرسانی ناموفق بود", "gate_continue" to "ادامه", "gate_continue_offline" to "ادامه به‌صورت آفلاین",
        "gate_recheck" to "بررسی دوباره", "gate_open_page" to "صفحه‌ی نسخه",
        "gate_footer" to "لانچر غیررسمی ماینکرافت از استودیو ObsiFox",
        "gate_footer_offline" to "نسخه‌ی آفلاین — بدون بررسی به‌روزرسانی و هنر آنلاین",
        // living theme
        "stat_install" to "نصب", "stat_playtime" to "زمان بازی", "stat_last" to "آخرین بازی",
        "ready_status" to "آماده", "offline_status" to "آفلاین", "art_loading" to "در حال دانلود هنر رسمی…", "fs_toggle" to "تمام‌صفحه",
        "theme_vanilla" to "وانیلا", "theme_vanilla_desc" to "سطح‌های تیره‌ی گرم با نارنجی کلاسیک",
        "theme_white" to "روشن", "theme_white_desc" to "سطح روشن و آرام برای اتاق روشن",
        "theme_black" to "مشکی", "theme_black_desc" to "تقریباً مشکی، برای اتاق تاریک",
        "appearance" to "ظاهر", "appearance_hint" to "پوسته، هنر لانچر و نحوه‌ی ترکیب‌شان.",
        "bg_version" to "هماهنگ با پروفایل", "bg_version_desc" to "وال‌پیپر رسمی نسخه‌ی ماینکرافتِ پروفایل انتخابی",
        "bg_latest" to "همیشه جدیدترین", "bg_latest_desc" to "جدیدترین وال‌پیپر رسمی در همه‌ی صفحه‌ها",
        "bg_custom" to "تصویر خودم", "bg_custom_desc" to "یک PNG یا JPG از دیسکت انتخاب کن",
        "bg_pick" to "انتخاب تصویر وال‌پیپر",
        "bg_version_old" to "پروفایل‌های قدیمی‌تر از ۱.۱۲.۲ از بسته‌ی وال‌پیپر کلاسیک PC استفاده می‌کنند.",
        "adapt_colors" to "هماهنگی رنگ‌ها با هنر", "adapt_colors_desc" to "لانچر رنگ تاکیدی‌اش را از پالت وال‌پیپر می‌گیرد.",
        "video_note" to "وال‌پیپر ویدیویی در به‌روزرسانی بعدی می‌آید.",
        // first-run wizard
        "continue" to "ادامه", "wiz_first" to "اولین اجرا", "wiz_steps" to "مراحل",
        "wiz_step_theme" to "پوسته", "wiz_step_bg" to "هنر لانچر", "wiz_step_acc" to "حساب محلی",
        "wiz_hint" to "همه‌ی این‌ها را بعداً می‌توانی در تنظیمات عوض کنی.",
        "wiz_kicker" to "به ObsiLauncher خوش آمدی", "wiz_t1" to "یک ظاهر انتخاب کن", "wiz_d1" to "پوسته‌ی سطح لانچر.",
        "wiz_t2" to "پس‌زمینه چه نشان بدهد؟", "wiz_d2" to "وال‌پیپرهای رسمی ماینکرافت، هماهنگ با پروفایل‌هایت.",
        "wiz_t3" to "یک حساب محلی اضافه کن", "wiz_d3" to "فقط حساب آفلاین — روی همین دستگاه ذخیره می‌شود.",
        "wiz_step_of" to "گام %d از ۳", "wiz_finish" to "پایان", "account_empty" to "هنوز حساب محلی‌ای نداری.",
        "local_only_note" to "حساب‌ها فقط روی همین دستگاه ذخیره می‌شوند؛ بدون ورود مایکروسافت و بدون سرور خارجی.",
    )
}
